SELECT DBTIMEZONE FROM DUAL;
SELECT SESSIONTIMEZONE FROM DUAL;

SELECT * FROM FIRST_ENTITY;

DECLARE
    entities FIRST_ENTITY%ROWTYPE;
BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET TIME_ZONE=''UTC''';
    SELECT * INTO entities FROM FIRST_ENTITY;
    DBMS_OUTPUT.PUT_LINE(entities.CREATE_TIMESTAMP);
END;